{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "kafka-minion.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-minion.name" . }}
    helm.sh/chart: {{ include "kafka-minion.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kafka-minion.fullname" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccount.create  }}
  name: {{ include "kafka-minion.fullname" . }}
  {{- else }}
  name: {{ .Values.serviceAccount.name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{- end }}
