
{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafka-minion.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "kafka-minion.name" . }}
    chart: {{ template "kafka-minion.chart" . }}
    release: {{ if .Values.serviceMonitor.additionalLabels -}}
      {{- .Release.Name -}}
    {{- else -}}
      {{- .Values.serviceMonitor.releaseLabel -}}
    {{- end }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceMonitor.additionalLabels }}
{{- range $key, $value := .Values.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    port: http
    path: /metrics
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
    {{ toYaml .Values.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceMonitor.honorLabels }}
    honorLabels: {{ .Values.serviceMonitor.honorLabels }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kafka-minion.name" . }}
{{- end }}
