{{- if and (.Values.kafka.tls.enabled) (not .Values.kafka.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka-minion.tlsSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "kafka-minion.name" . }}
    chart: {{ include "kafka-minion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.extraLabels }}
    {{ toYaml .Values.extraLabels | nindent 4 }}
    {{- end }}
type: Opaque
data:
  tls.ca: {{ .Values.kafka.tls.certificates.ca | b64enc }}
  tls.key: {{ .Values.kafka.tls.certificates.key | b64enc }}
  tls.crt: {{ .Values.kafka.tls.certificates.certificate | b64enc }}
  passphrase: {{ .Values.kafka.tls.certificates.passphrase | b64enc }}
{{- end -}}
